### PR TITLE
Review and Member Controllers created.

### PR DESCRIPTION
**Pull request by MatthewK286**
Issues #116 #117

### CODE REVIEW

**Comment by MatthewK286** [comment]
Solves #116 #117

**Comment by MatthewK286** [comment]
I will add javadoc in the afternoon.

**Comment by melanger** [comment]
You forgot to edit tests to match the new Facade interfaces. `memberFacade.removeMember(member);` should change to `memberFacade.removeMember(memberId);` etc. plus you need the Id to be set after calling `service.create` - see what I did in [createTourTest](https://github.com/melanger/pa165-photography-club/blob/master/pa165-photography-club-service/src/test/java/cz/muni/fi/pa165/photographyclub/facade/TourFacadeTest.java).

**Review by melanger — CHANGES_REQUESTED** [review]
Otherwise it's nice :) Just a few notes.
- [ ] I wonder if `findMemberByName` should return a List... but anyway, `name` should be a query parameter and the `RequestMapping` value should be default = not set (e.g. calling `/members/?name=John%20Doe` instead of `/members/John%Doe`)
- [ ] `getReviewsByAuthor` has the same URL mapping as `getReviewsByTour` and `getReviewById`. I would use `getReviewsByAuthor` actually in `MemberController` with mapping `/members/{id}/reviews`, instead of current `/reviews/{id}` or whatever; and `getReviewsByTour` in `TourController` as `/tours/{id}/reviews` - but actually there is also `tourFacade.getTourReviews` and it's already used for that endpoint, so you can (IMHO) delete the method with `getReviewsByTour` from `ReviewController` (note: we have this kind of bad design also in `getEquipmentByMember`, I'm going to fix that, too)
- [ ] `updateReview` should have `RequestMethod.PUT`

**Comment by melanger** [comment]
OK, I'll do it then.

**Comment by melanger** [comment]
This is done, @MatthewK286, move on to #135

**Review by melanger — APPROVED** [review]

**Pull request merged**
