### PR TITLE
Fixed tour list in member. This was throwing null pointer exception f…

### PR DESCRIPTION
**Pull request by DenisFigula**
…or me

### CODE REVIEW

**Comment by melanger** [comment]
I addressed this by changing your SampleData and not setting null. I think that this field should never be null, it should be an empty list.

**Comment by DenisFigula** [comment]
Sorry, but i dont understand. What do you suggest please ?

**Comment by melanger** [comment]
I already fixed this in one of the branches, I left Member as it is and I changed the reason of the NullPointerException, which was in SampleDataFacadeImpl where you were setting tours and reviews to be null. I changed that to empty lists, so this fix is not needed, and I also think that you should not call member.setTours(null) ever, you should do member.setTours(Collections.emptyList()) - not sure about the syntax, sorry for typos.

**Comment by melanger** [comment]
I recommend closing this pull request and try merging master into your feature branches in progress, if the fix is not there.

**Comment by DenisFigula** [comment]
I understand now, thanks. Closing this request

**Pull request closed without merging**
