### PR TITLE
Updated createEquipment so it returns ID.

### PR DESCRIPTION
**Pull request by DenisFigula**
Added curls for Equipment rest, will be updated when member is available

### CODE REVIEW

**Comment by DenisFigula** [comment]
I changed create equipment method so it returns id of new equipment.
I am not sure if it's desired of not and if yes if there needs to be other changes in code, i.e. in tests

**Comment by melanger** [comment]
Well, there is a simple way to find out :)
`mvn clean install`

`Results :
Failed tests: addEquipmentToMemberTest(cz.muni.fi.pa165.photographyclub.facade.EquipmentFacadeTest)
java.lang.NullPointerException at cz.muni.fi.pa165.photographyclub.facade.EquipmentFacadeImpl.createEquipment(EquipmentFacadeImpl.java:59) at cz.muni.fi.pa165.photographyclub.facade.EquipmentFacadeTest.addEquipmentToMemberTest(EquipmentFacadeTest.java:142)`

**Review by melanger — CHANGES_REQUESTED** [review]
The point is to make `service.create` set the ID on the entity. Take a look at `TourFacadeTest.createTourTest()` and the usage of `doAnswer`. I can also edit the test if you need help.

**Comment by melanger** [comment]
Also:
- [x] please edit the javadoc of EquipmentFacade (add the return tag)
- [x] `equipmentFacade.createEquipment` may return `PhotoEntityNotFoundException` (subclass of EntityNotFoundException) if the desired owner of the equipment does not exist. Also, equality of Equipment instances is based on ID, so it's not possible that the new equipment will already exist, since the ID is set automatically to a new one. Prove me wrong :) or change the `catch` in the body of `createEquipment` back
- [x] and in the examples (cURL.md), please write real values, not placeholders (that's what belongs into apiary.apib, I'll handle that). E.g. instead of `http://localhost:8080/pa165/rest/members/{member_id}` write `http://localhost:8080/pa165/rest/members/1` (if this member exists?) and include the real response as I did (I think this is better for the reviewing people, they can run the commands right away).

**Comment by DenisFigula** [comment]
Test updated

**Comment by melanger** [comment]
One more thing, since I think that `getEquipmentByMember` should be available under `/rest/members/{member_id}/equipment` (now it's `/rest/equipment/members/{member_id}`), I will move it to MemberController.

**Comment by melanger** [comment]
I wasn't able to build with your starred `import org.springframework.web.bind.annotation.*`, so I replaced it back, sorry.

**Comment by melanger** [comment]
And I did some changes, including adding the `ownerId`, so I finally got it working including the cURL commands, which were not...

**Review by melanger — APPROVED** [review]

**Pull request merged**
