### PR TITLE
Feature/figula/tour facade impl

### PR DESCRIPTION
**Pull request by DenisFigula**
getTourParticipants is commented for now, i just dont know how to implement it. I think there is a missing method in TourService or i just dont know. If you know how, that's great, otherwise let's delete this method
I also added something into pom because my IDE was complaining about LocalDate, so we can delete it if it makes any trouble

### CODE REVIEW

**Comment by DenisFigula** [comment]
closes #64

**Comment by MatthewK286** [comment]
when creating Tour there is no reason to add review or participants(this can be debatable but since admin creates tour i think he will not add participants) that is why i did not add them to TourCreateDTO so i think you shouldn't add them

**Comment by melanger** [comment]
I implemented the getTourParticipants method, if I am not missing something, it is quite simple :) Please review the commented out code in tests (e.g. remove it) and adjust (create) tests accordingly.

**Comment by DenisFigula** [comment]
Thanks guys, i should have known that. Test for it added

**Review by melanger — APPROVED** [review]

**Pull request merged**
