### PR TITLE
TourDao and TourDao implementation created

### PR DESCRIPTION
**Pull request by DenisFigula**

### CODE REVIEW

**Review by melanger — CHANGES_REQUESTED** [review]
Please add "proper javadoc" as required by the project requirements. Also please use " closes #4" in your commit message.

**Comment by DenisFigula** [comment]
@author NAME javadoc present in classes, should there be anything else ?

**Comment by melanger** [comment]
In the class javadoc I would include a short description. I am also used to writing javadoc for (all) methods, at least the arguments (with their types) = "the contract". If there is a reasonable description of a method and/or arguments (which says something more than the names), I include that as well.

**Comment by DenisFigula** [comment]
javadoc added

**Comment by melanger** [comment]
Please "git push" it, I cannot see any new commits.

**Comment by DenisFigula** [comment]
i have rebased it and squashed commits into one

**Comment by melanger** [comment]
Oh, OK. This should be (more than) sufficient.

**Review by melanger — APPROVED** [review]

**Pull request merged**
