### PR TITLE
Removed unused variable from findAllEquipmentTest

### PR DESCRIPTION
**Pull request by melanger**

### CODE REVIEW

**Comment by MatthewK286** [comment]
Variable is needed in case that test inside class are independent on each other.... (witch they are not currently, but probably should be....)

**Comment by melanger** [comment]
Does `makeEquipment` do something, which is needed by the `findAllEquipmentTest`?

**Comment by MatthewK286** [comment]
It creates equipment and stores it to the database.

**Comment by melanger** [comment]
I must be missing something, but you assert euqipList to be empty (and the test still passes), so I do not see the reason to call `makeEquipment` in the `findAllEquipmentTest`:
```java
@Test
public void findAllEquipmentTest(){
  // Equipment equipment = makeEquipment();

  List<Equipment> euqipList = service.findAllEquipment();
  Assert.assertNotNull(euqipList);
  Assert.assertNotEquals(euqipList.size(), 0);
}
```

**Comment by MatthewK286** [comment]
Assert.assertNotEquals(euqipList.size(), 0);    "NotEquals" I assert it NOT to be empty.

**Comment by melanger** [comment]
That's what I was missing, thanks for clarifying :) I changed the code and removed only the variable, not the call.

**Review by DenisFigula — APPROVED** [review]

**Pull request merged**
