### PR TITLE
Feature/kravec/tour review facade

### LINKED ISSUE #59: create api>ReviewFacade and associated DTOs
- [ ] Everything that should happen in the system must be available through these interfaces (create entities, deleting them etc)
- [ ] All the classes must be wired via dependency injection. Your service objects should obtain an instance of the EntityManager that way
- [ ] All the facade interfaces must not reference entities, but Transfer Objects only
- [ ] use Dozer framework to map entity instances to transfer objects. The mapping may be done on Facade Layer
- [ ] Facade layer is used to drive transactions

### PR DESCRIPTION
**Pull request by MatthewK286**
Closes #59 #60

### CODE REVIEW

**Review by melanger — COMMENTED** [review]
Tests in service.MemberServiceTest fail on my machine, do they pass on yours?

**Comment by MatthewK286** [comment]
I am currently traveling so i will look at it later, but none of service tests worked on my machine

**Comment by MatthewK286** [comment]
But that is comment for different pull request

**Comment by melanger** [comment]
You are not writing tests the right way I think. Please check out for example TourServiceTest class. You should not call memberDao (that's a mock object), but call methods on memberService (which gets the mock memberDao and calls its methods) and then see what was called on the DAO or prepare (mock) a method in advance and then test the result (which propagates as a result of the memberService call).

Instead of:
```java
memberDao.create(member);
Assert.assertEquals(memberService.findById(member.getId()), member);
```

I think you should consider:
```java
final long id = 42l;
member.setId(id);
when(memberDao.findById(id)).thenReturn(member);

Assert.assertEquals(memberService.findById(id), member);
```

etc.

**Review by melanger — CHANGES_REQUESTED** [review]
Please fix the tests, at least so that the project builds.

**Comment by MatthewK286** [comment]
I will look at it, but merge this request so we can continue. i will create new pull request when i do the fix. The class we are talking about i already in the master branch so not merging this branch because of that class is not helping anything

**Review by DenisFigula — DISMISSED** [review]

**Review by melanger — APPROVED** [review]

**Pull request merged**
