### PR TITLE
In memory DB

### LINKED ISSUE #21: create in-memory DB for testing
Please, one of you create the in-memory DB for testing (and make ReviewDaoTest run).

### PR DESCRIPTION
**Pull request by DenisFigula**
closes #21

### CODE REVIEW

**Comment by melanger** [comment]
Did you make ReviewDaoTest run?

**Comment by melanger** [comment]
(or yours)

**Comment by DenisFigula** [comment]
no, it fails to load Application context

**Comment by melanger** [comment]
That is exactly what I asked to solve... Can you debug it? Or @MatthewK286 ?

**Comment by melanger** [comment]
Also, you have a typo there: InMem**e**ryDatabase

**Comment by DenisFigula** [comment]
I am trying, but without luck so far

**Comment by DenisFigula** [comment]
I tried creating application context and persitance.xml but it still doesnt work

**Comment by MatthewK286** [comment]
I have it sort of working but, but tests would probably need some changes to work i think.... 
I will try to make it work better and i will push it when i finish today(even if it's not fully working), so you can review it tomorrow morning

**Comment by MatthewK286** [comment]
So with some changes to test file I got ReviewDaoTest to work.

**Comment by melanger** [comment]
Solved by 69804e2798523e7656e7f1e0766f0c0c5afc64b0 (#29)

**Pull request closed without merging**
