### PR TITLE
Implemented TourController

### LINKED ISSUE #118: create and implement rest.TourController
see EquipmentController

### PR DESCRIPTION
**Pull request by DenisFigula**
closes #118

### CODE REVIEW

**Review by melanger — CHANGES_REQUESTED** [review]
Review bodies of getTourReviews, getTourParticipants and getTourRating, similar things apply to other methods and #123

**Comment by melanger** [comment]
Which exception are you catching in `try { tourFacade.getAllTours }` ? Please make a cURL command that uses this endpoint and the response is 404 (I don't think it's possible).

**Comment by melanger** [comment]
Write the cURL command at least for yourself to test this.

**Comment by melanger** [comment]
@DenisFigula We really need to move on. With your `catch (Exception e)` you were hiding errors, that's exactly why you should almost never use it. The real problem was with Dozer not able to map `LocalDate` instances, I fixed that and now it works. It cannot throw (in normal situations), so there's no need to catch.

**Comment by DenisFigula** [comment]
Sorry about that, i was just lloking into it. Are there any other wrong catch blocks ?

**Review by melanger — APPROVED** [review]

**Comment by melanger** [comment]
Not here, but in branch feature/figula/restEquipment in EquipmentController in getEquipmentByMember. Please compare EquipmentController to TourController and adjust it accordingly (I think that's the easiest way).

**Pull request merged**
